#coding: utf-8
import re

#科目字典
subjects = {1:'语文',2:'数学',3:'英语','4':'物理','5':'化学','6':'生物','7':'政治','8':'历史','9':'地理'}

#题型字典
ques_types = {1:
                {
                    1 : { 'name' : '选择题', 'option' : '1' ,},
                    2 : { 'name' : '填空题', 'option' : '0'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '匹配题', 'option' : '0'},
                    5 : { 'name' : '古诗文阅读题', 'option' : '0'},
                    6 : { 'name' : '现代文阅读题', 'option' : '0'},
                    7 : { 'name' : '作文题', 'option' : '0'},
                    8 : { 'name' : '语言表达', 'option' : '0'},
                    9 : { 'name' : '综合性学习', 'option' : '0'},
                    10 : { 'name' : '名著导读', 'option' : '0'},
                    11 : { 'name' : '其他', 'option' : '0'},
                    12 : { 'name' : '多选题', 'option' : '3'},
                },
                2:
                {
                    1 : { 'name' : '单项选择题', 'option' : '1'},
                    2 : { 'name' : '填空题', 'option' : '0'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '匹配题', 'option' : '0'},
                    5 : { 'name' : '解答题', 'option' : '0'},
                    6 : { 'name' : '作图操作题', 'option' : '0'},
                    7 : { 'name' : '计算题', 'option' : '0'},
                    8 : { 'name' : '证明题', 'option' : '0'},
                    9 : { 'name' : '多选题', 'option' : '3'},
                },
                3:
                {
                    1 : { 'name' : '单项选择题', 'option' : '1'},
                    2 : { 'name' : '填空题', 'option' : '0'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '是非题', 'option' : '2'},
                    5 : { 'name' : '完形填空题', 'option' : '1'},
                    6 : { 'name' : '阅读理解题', 'option' : '1'},
                    7 : { 'name' : '作文题', 'option' : '0'},
                    8 : { 'name' : '翻译题', 'option' : '0'},
                    9 : { 'name' : '选词填空题', 'option' : '0'},
                    10 : { 'name' : '短文改错题', 'option' : '0'},
                    11 : { 'name' : '七选五题', 'option' : '4'},
                    12 : { 'name' : '听力题', 'option' : '0'},
                    13 : { 'name' : '匹配题', 'option' : '0'},
                    14 : { 'name' : '改错', 'option' : '0'},
                    15 : { 'name' : '其他', 'option' : '0'},
                    16 : { 'name' : '多选题', 'option' : '3'},
                },
                4:
                {
                    1 : { 'name' : '选择题', 'option' : '1'},
                    2 : { 'name' : '多项选择题', 'option' : '3'},
                    3 : { 'name' : '填空题', 'option' : '0'},
                    4 : { 'name' : '简答题', 'option' : '0'},
                    5 : { 'name' : '计算题', 'option' : '0'},
                    6 : { 'name' : '作图题', 'option' : '0'},
                    7 : { 'name' : '实验探究题', 'option' : '0'},
                },
                5:
                {
                    1 : { 'name' : '选择题', 'option' : '1'},
                    2 : { 'name' : '多选题', 'option' : '3'},
                    3 : { 'name' : '填空题', 'option' : '0'},
                    4 : { 'name' : '简答题', 'option' : '0'},
                    5 : { 'name' : '计算题', 'option' : '0'},
                    6 : { 'name' : '实验题(客观单选)', 'option' : '1'},
                    7 : { 'name' : '实验题(客观多选)', 'option' : '3'},
                    8 : { 'name' : '实验题(主观)', 'option' : '0'},
                    9 : { 'name' : '推断题(客观单选)', 'option' : '1'},
                    10 : { 'name' : '推断题(客观多选)', 'option' : '3'},
                    11 : { 'name' : '推断题(主观)', 'option' : '0'},
                },
                6:
                {
                    1 : { 'name' : '单选题', 'option' : '1'},
                    2 : { 'name' : '多选题', 'option' : '3'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '匹配题', 'option' : '0'},
                    5 : { 'name' : '填空题', 'option' : '0'},
                    6 : { 'name' : '综合题', 'option' : '0'},
                    7 : { 'name' : '探究题', 'option' : '0'},
                },
                7:
                {
                    1 : { 'name' : '选择题', 'option' : '1'},
                    2 : { 'name' : '多选题', 'option' : '3'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '填空题', 'option' : '0'},
                    5 : { 'name' : '简答题', 'option' : '0'},
                    6 : { 'name' : '论述题', 'option' : '0'},
                    7 : { 'name' : '匹配题', 'option' : '0'},
                },
                8:
                {
                    1 : { 'name' : '单选题', 'option' : '1'},
                    2 : { 'name' : '多选题', 'option' : '3'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '匹配题', 'option' : '0'},
                    5 : { 'name' : '填空题', 'option' : '0'},
                    6 : { 'name' : '改错题', 'option' : '0'},
                    7 : { 'name' : '材料分析题', 'option' : '0'},
                    8 : { 'name' : '简答题', 'option' : '0'},
                },
                9:
                {
                    1 : { 'name' : '选择题', 'option' : '1'},
                    2 : { 'name' : '多选题', 'option' : '3'},
                    3 : { 'name' : '判断题', 'option' : '2'},
                    4 : { 'name' : '匹配题', 'option' : '0'},
                    5 : { 'name' : '填空题', 'option' : '0'},
                    6 : { 'name' : '简答题', 'option' : '0'},
                    7 : { 'name' : '作图题', 'option' : '0'},
                    8 : { 'name' : '综合题', 'option' : '0'},
                }
            }

#是否是选择题1 判断题2 多选3其他0
ques_types_group = {1: {1: [1], 2: [3], 3: [12], },
                    2: {1: [1], 2: [3], 3: [9], },
                    3: {1: [1,5,6], 2: [3,4], 3: [16], },
                    4: {1: [1], 2: [], 3: [2], },
                    5: {1: [1], 2: [], 3: [2], },
                    6: {1: [1], 2: [3], 3: [2], },
                    7: {1: [1], 2: [3], 3: [2], },
                    8: {1: [1], 2: [3], 3: [2], },
                    9: {1: [1], 2: [3], 3: [2], }}
def ques_types_class(qtypes,subject):
    if(qtypes):
        for lableId,tyeps in ques_types_group[subject].items():
            if(qtypes in tyeps):
                return lableId
    return 0

#题型匹配关键字
key_words = {   1:
                [
                    {'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '1', 'key_word' : '语言文字运用', 'full_word' : '语言文字运用'},
                    {'type' : '1', 'key_word' : '选择正确的', 'full_word' : '选择正确的题项'},
                    {'type' : '1', 'key_word' : '选出词语', 'full_word' : '选出词语的正确读音'},
                    {'type' : '1', 'key_word' : '选出词语', 'full_word' : '选出词语的正确意思'},
                    {'type' : '2', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '2', 'key_word' : '基础知识及语言表达', 'full_word' : '基础知识及语言表达'},
                    {'type' : '2', 'key_word' : '基础知识', 'full_word' : '基础知识'},
                    {'type' : '2', 'key_word' : '基础运用', 'full_word' : '基础运用'},
                    {'type' : '2', 'key_word' : '语言文字运用', 'full_word' : '语言文字运用'},
                    {'type' : '2', 'key_word' : '空缺部分', 'full_word' : '补写出下列名句名篇中的空缺部分'},
                    {'type' : '2', 'key_word' : '空缺部分', 'full_word' : '补出下列句子中的空缺部分'},
                    {'type' : '2', 'key_word' : '填写恰当的语段', 'full_word' : '在下面一段文字横线处填写恰当的语段'},
                    {'type' : '2', 'key_word' : '名篇名句默写', 'full_word' : '名篇名句默写'},
                    {'type' : '2', 'key_word' : '名句默写', 'full_word' : '名句默写'},
                    {'type' : '2', 'key_word' : '默写名句', 'full_word' : '默写名句'},
                    {'type' : '2', 'key_word' : '古诗文默写', 'full_word' : '古诗文默写'},
                    {'type' : '2', 'key_word' : '默写', 'full_word' : '默写'},
                    {'type' : '2', 'key_word' : '默写古诗文', 'full_word' : '默写古诗文'},
                    {'type' : '2', 'key_word' : '拼音写汉字', 'full_word' : '根据拼音写汉字'},
                    {'type' : '2', 'key_word' : '填空', 'full_word' : '按要求填空'},
                    {'type' : '2', 'key_word' : '填空', 'full_word' : '按课文内容填空'},
                    {'type' : '2', 'key_word' : '写词语', 'full_word' : '看拼音，写词语'},
                    {'type' : '2', 'key_word' : '拼音填空', 'full_word' : '根据拼音填空'},
                    {'type' : '2', 'key_word' : '活学活用', 'full_word' : '活学活用'},
                    {'type' : '2', 'key_word' : '给加点字注音', 'full_word' : '给加点字注音'},
                    {'type' : '2', 'key_word' : '组词', 'full_word' : '组词'},
                    {'type' : '2', 'key_word' : '排序', 'full_word' : '排序'},
                    {'type' : '2', 'key_word' : '词类活用', 'full_word' : '词类活用（近义词反义词等）'},
                    {'type' : '2', 'key_word' : '按要求写词语', 'full_word' : '按要求写词语'},
                    {'type' : '2', 'key_word' : '修改错别字', 'full_word' : '修改错别字'},
                    {'type' : '2', 'key_word' : '修改句子', 'full_word' : '修改句子'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题'},
                    {'type' : '4', 'key_word' : '匹配', 'full_word' : '匹配题'},
                    {'type' : '4', 'key_word' : '连起来', 'full_word' : '将相对应的作家国别及作品连起来'},
                    {'type' : '4', 'key_word' : '连线', 'full_word' : '连线'},
                    {'type' : '4', 'key_word' : '词语匹配', 'full_word' : '词语匹配'},
                    {'type' : '5', 'key_word' : '古诗文阅读', 'full_word' : '古诗文阅读题'},
                    {'type' : '5', 'key_word' : '文言文阅读', 'full_word' : '文言文阅读'},
                    {'type' : '5', 'key_word' : '古诗阅读', 'full_word' : '古诗阅读'},
                    {'type' : '5', 'key_word' : '古文阅读', 'full_word' : '古文阅读'},
                    {'type' : '5', 'key_word' : '古代诗文阅读', 'full_word' : '古代诗文阅读'},
                    {'type' : '5', 'key_word' : '古代诗歌阅读', 'full_word' : '古代诗歌阅读'},
                    {'type' : '5', 'key_word' : '阅读下面一首诗', 'full_word' : '阅读下面一首诗，完成题目'},
                    {'type' : '5', 'key_word' : '古诗词鉴赏', 'full_word' : '古诗词鉴赏'},
                    {'type' : '5', 'key_word' : '诗词鉴赏', 'full_word' : '诗词鉴赏'},
                    {'type' : '5', 'key_word' : '古诗赏析', 'full_word' : '古诗赏析'},
                    {'type' : '5', 'key_word' : '古诗词赏析', 'full_word' : '古诗词赏析'},
                    {'type' : '6', 'key_word' : '现代文阅读', 'full_word' : '现代文阅读题'},
                    {'type' : '6', 'key_word' : '阅读下列的文章', 'full_word' : '阅读下列的文章，按要求作答。'},
                    {'type' : '6', 'key_word' : '课外阅读', 'full_word' : '课外阅读'},
                    {'type' : '6', 'key_word' : '论述类文本阅读', 'full_word' : '论述类文本阅读'},
                    {'type' : '6', 'key_word' : '实用类文本阅读', 'full_word' : '实用类文本阅读'},
                    {'type' : '6', 'key_word' : '文学类文本阅读', 'full_word' : '文学类文本阅读'},
                    {'type' : '7', 'key_word' : '作文', 'full_word' : '作文题'},
                    {'type' : '7', 'key_word' : '写作', 'full_word' : '写作（二选一）,写作园地'},
                    {'type' : '7', 'key_word' : '作文', 'full_word' : '写作园地'},
                    {'type' : '7', 'key_word' : '看图说话', 'full_word' : '看图说话'},
                    {'type' : '7', 'key_word' : '习作练习', 'full_word' : '习作练习'},
                    {'type' : '8', 'key_word' : '语言表达', 'full_word' : '语言表达'},
                    {'type' : '8', 'key_word' : '仿写句子，使句子连贯', 'full_word' : '仿写句子，使句子连贯'},
                    {'type' : '8', 'key_word' : '仿照例句的形式', 'full_word' : '仿照例句的形式，在横线处填上恰当的语句'},
                    {'type' : '8', 'key_word' : '组成语意连贯的一段话', 'full_word' : '仿照下面画线句子续写两句话，组成语意连贯的一段话。'},
                    {'type' : '8', 'key_word' : '口语交际', 'full_word' : '口语交际'},
                    {'type' : '9', 'key_word' : '综合性学习', 'full_word' : '综合性学习'},
                    {'type' : '10', 'key_word' : '名著导读', 'full_word' : '名著导读'},
                    {'type' : '10', 'key_word' : '名著阅读', 'full_word' : '名著阅读'},
                    {'type' : '12', 'key_word' : '多选题', 'full_word' : '多选题'},
                ],
                2:
                [
                    {'type' : '1', 'key_word' : '单项选择', 'full_word' : '单项选择题'},
                    {'type' : '1', 'key_word' : '选择', 'full_word' : '单项选择题'},
                    {'type' : '1', 'key_word' : '火眼金睛辨真假', 'full_word' : '火眼金睛辨真假'},
                    {'type' : '1', 'key_word' : '选一选', 'full_word' : '选一选'},
                    {'type' : '1', 'key_word' : '慧眼识金', 'full_word' : '慧眼识金'},
                    {'type' : '2', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '2', 'key_word' : '填一填', 'full_word' : '填一填'},
                    {'type' : '2', 'key_word' : '智力拼盘', 'full_word' : '智力拼盘'},
                    {'type' : '2', 'key_word' : '我会填', 'full_word' : '我会填'},
                    {'type' : '2', 'key_word' : '正确填写', 'full_word' : '正确填写'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题/判断正误'},
                    {'type' : '3', 'key_word' : '小法官', 'full_word' : '我是小法官/请你来做个公正的小法官'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '辨一辨'},
                    {'type' : '4', 'key_word' : '匹配', 'full_word' : '匹配'},
                    {'type' : '5', 'key_word' : '解答', 'full_word' : '解答题/解答下列题目/用适当的方法解答下列各题'},
                    {'type' : '5', 'key_word' : '列式计算', 'full_word' : '列式计算/只列式不计算'},
                    {'type' : '5', 'key_word' : '求阴影部分的面积', 'full_word' : '求阴影部分的面积'},
                    {'type' : '5', 'key_word' : '综合运用', 'full_word' : '综合运用'},
                    {'type' : '5', 'key_word' : '动手操作', 'full_word' : '动手操作'},
                    {'type' : '5', 'key_word' : '解决问题', 'full_word' : '解决问题'},
                    {'type' : '5', 'key_word' : '生活中的数学问题', 'full_word' : '生活中的数学问题'},
                    {'type' : '5', 'key_word' : '计算', 'full_word' : '计算题'},
                    {'type' : '5', 'key_word' : '应用', 'full_word' : '应用题'},
                    {'type' : '5', 'key_word' : '证明', 'full_word' : '证明题'},
                    {'type' : '5', 'key_word' : '化简求值', 'full_word' : '化简求值'},
                    {'type' : '5', 'key_word' : '附加', 'full_word' : '附加题'},
                    {'type' : '6', 'key_word' : '操作', 'full_word' : '作图操作题/操作题/操作应用'},
                    {'type' : '6', 'key_word' : '作图', 'full_word' : '作图操作题/作图/尺规作图'},
                    {'type' : '6', 'key_word' : '画一画', 'full_word' : '画一画'},
                    {'type' : '7', 'key_word' : '计算', 'full_word' : '计算题'},
                    {'type' : '7', 'key_word' : '直接写出得数', 'full_word' : '直接写出得数'},
                    {'type' : '7', 'key_word' : '计算', 'full_word' : '计算题/递等式计算/脱式计算'},
                    {'type' : '7', 'key_word' : '计算', 'full_word' : '口算'},
                    {'type' : '7', 'key_word' : '计算', 'full_word' : '估算'},
                    {'type' : '7', 'key_word' : '简便运算', 'full_word' : '简便运算'},
                    {'type' : '7', 'key_word' : '简算', 'full_word' : '简算/能简算的要简算'},
                    {'type' : '7', 'key_word' : '解方程', 'full_word' : '解方程（组）'},
                    {'type' : '7', 'key_word' : '解不等式', 'full_word' : '解不等式（组）'},
                    {'type' : '7', 'key_word' : '求x的值', 'full_word' : '求x的值'},
                    {'type' : '7', 'key_word' : '因式分解', 'full_word' : '因式分解'},
                    {'type' : '7', 'key_word' : '化简', 'full_word' : '化简'},
                    {'type' : '7', 'key_word' : '解比例', 'full_word' : '解比例'},
                    {'type' : '8', 'key_word' : '证明', 'full_word' : '证明题'},
                    {'type' : '9', 'key_word' : '多选', 'full_word' : '多选题'},

                ],
                3:
                [
                    {'type' : '1', 'key_word' : '单项选择', 'full_word' : '单项选择'},
                    {'type' : '2', 'key_word' : r'^.*?(?!完形)填空.*?$', 'full_word' : '填空/语法填空/阅读填空/句意填空/用was 或 were 填空/用所给词的适当（正确）形式填空/用适当的介词填空/看图填空'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题/根据短文内容，判断正（T）误（F）。'},
                    {'type' : '5', 'key_word' : '完形填空', 'full_word' : '完形填空'},
                    {'type' : '6', 'key_word' : '阅读理解', 'full_word' : '阅读理解题/阅读理解能力测试/阅读理解并选择适合的选项'},
                    {'type' : '7', 'key_word' : '作文', 'full_word' : '作文题/情景作文'},
                    {'type' : '8', 'key_word' : '翻译', 'full_word' : '翻译题/翻译下列句子/将下列句子翻译成中文/将下列句子翻译成英文/语篇翻译，阅读下面短文，将划线部分译成英文或中文'},
                    {'type' : '9', 'key_word' : '选词填空', 'full_word' : '选词填空'},
                    {'type' : '10', 'key_word' : '改错', 'full_word' : '短文改错/改错题'},
                    {'type' : '11', 'key_word' : r'^.*?七.*?五.*?$', 'full_word' : '七选五/七选五题/七选五阅读'},
                    {'type' : '12', 'key_word' : '听力', 'full_word' : '听力/听力部分/听力理解/听力测试/听力技能'},
                    {'type' : '13', 'key_word' : '匹配题', 'full_word' : '匹配题'},
                    {'type' : '14', 'key_word' : '改错', 'full_word' : '改错/短文改错'},

                    {'type' : '1', 'key_word' : '最佳选项', 'full_word' : '根据句意，从下面各题所给的A、B、C三个选项中，选择可以填入空白处的最佳选项。'},
                    {'type' : '1', 'key_word' : '选出每组中不同类', 'full_word' : '选出每组中不同类的单词。'},
                    {'type' : '1', 'key_word' : r'^.*?选择正确的答案(?!对话).*?$', 'full_word' : '选择正确的答案，并将其序号填入括号内。/选择正确的答案补全单词/根据情景选择正确的答案'},
                    {'type' : '1', 'key_word' : '看图选择合适的', 'full_word' : '看图选择合适的单词或短语完成句子, 将序号填入括号内.'},
                    {'type' : '1', 'key_word' : '选出与所给单词同属一类的单词', 'full_word' : '选出与所给单词同属一类的单词'},
                    {'type' : '1', 'key_word' : '按要求选择单词的正确形式', 'full_word' : '按要求选择单词的正确形式'},
                    {'type' : '1', 'key_word' : '选择最佳答案', 'full_word' : '选择最佳答案'},
                    {'type' : '1', 'key_word' : '选择句子的最佳译文', 'full_word' : '选择句子的最佳译文'},
                    {'type' : '1', 'key_word' : '按要求改写句子', 'full_word' : '按要求改写句子'},
                    {'type' : '1', 'key_word' : '选择与图片相符的句子', 'full_word' : '选择与图片相符的句子'},
                    {'type' : '1', 'key_word' : '单词辨认', 'full_word' : '单词辨认：找出每组中不属于同一类的单词'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选'},
                    {'type' : '1', 'key_word' : '选择题', 'full_word' : '选择题'},
                    # {'type' : '1', 'key_word' : '词汇', 'full_word' : '词汇'},
                    {'type' : '1', 'key_word' : '语法', 'full_word' : '语法'},
                    {'type' : '1', 'key_word' : '最接近的选项', 'full_word' : '选出与句中划线部分意义最接近的选项'},
                    {'type' : '1', 'key_word' : '找出下列划线部分发音不同的单词', 'full_word' : '找出下列划线部分发音不同的单词'},
                    {'type' : '1', 'key_word' : 'choose the words according to the pictures', 'full_word' : 'Choose the words according to the pictures.'},
                    {'type' : '1', 'key_word' : 'choose the sentences according to the pictures', 'full_word' : 'Choose the sentences according to the pictures.'},
                    {'type' : '1', 'key_word' : 'read the text and choose the best answer', 'full_word' : 'Read the text and choose the best answer.'},
                    {'type' : '1', 'key_word' : '语音知识', 'full_word' : '语音知识'},
                    {'type' : '1', 'key_word' : '与给出的音标不同的一个', 'full_word' : '选出下面各组单词中划线部分与给出的音标不同的一个'},
                    {'type' : '1', 'key_word' : 'according to the passage, choose the best answer', 'full_word' : 'according to the passage, choose the best answer'},
                    
                    # {'type' : '2', 'key_word' : r'^.*?(?!完形)填空.*?$', 'full_word' : '填空/语法填空/阅读填空/句意填空/用was 或 were 填空/用所给词的适当（正确）形式填空/用适当的介词填空/看图填空'},
                    {'type' : '2', 'key_word' : '单词拼写', 'full_word' : '单词拼写'},
                    # {'type' : '2', 'key_word' : '词汇运用', 'full_word' : '词汇运用'},
                    {'type' : '2', 'key_word' : '句型转换', 'full_word' : '句型转换（每空一词）'},
                    {'type' : '2', 'key_word' : '填入', 'full_word' : '阅读下面短文，在空白处填入1个适当的单词或括号内单词的正确形式。'},
                    {'type' : '2', 'key_word' : '句意填词', 'full_word' : '句意填词'},
                    {'type' : '2', 'key_word' : '写出下列动词的过去式', 'full_word' : '写出下列动词的过去式'},
                    {'type' : '2', 'key_word' : '词汇', 'full_word' : '词汇/词汇运用'},
                    {'type' : '2', 'key_word' : '看音标写单词', 'full_word' : '看音标写单词'},
                    {'type' : '2', 'key_word' : '按要求写出下列单词', 'full_word' : '按要求写出下列单词'},
                    {'type' : '2', 'key_word' : '写出节日所在的时间', 'full_word' : '写出节日所在的时间'},
                    {'type' : '2', 'key_word' : '每空一词', 'full_word' : '完成句子，根据汉语提示完成句子，每空一词。'},
                    {'type' : '2', 'key_word' : 'fill in the blanks according to the story', 'full_word' : 'fill in the blanks according to the story'},
                    
                    # {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题/根据短文内容，判断正（T）误（F）。'},
                    {'type' : '3', 'key_word' : r'^.*?符合的.*?T.*?$', 'full_word' : '阅读下面的材料，判断下列句子是否符合材料内容。符合的写T，不符合的写F./根据短文内容,判断文后的句子是否符合短文内容,符合的填"T",不符合的填"F"'},
                    {'type' : '3', 'key_word' : r'^.*?括号内打.*?V.*?$', 'full_word' : '观察下面每组单词中划线部分的读音，相同的在题前的括号内打“V”，不同的打“X’。'},
                    {'type' : '3', 'key_word' : r'^.*?√.*?×.*?$', 'full_word' : '阅读短文，判断下列句子的对错，打上“√”或“×”。'},
                    {'type' : '3', 'key_word' : 'write T for true and F for false', 'full_word' : 'read the passage and write T for true and F for false.'},
                    
                    # {'type' : '5', 'key_word' : '完形填空', 'full_word' : '完形填空'},
                    {'type' : '5', 'key_word' : r'阅读下面短文.+?填入空白处的最佳选项', 'full_word' : '阅读下面短文，从短文后各题所给的A、B、C和D四个选项中，选出可以填入空白处的最佳选项'},
                    {'type' : '5', 'key_word' : '选择正确答案完成对话', 'full_word' : '选择正确答案完成对话'},

                    # {'type' : '6', 'key_word' : '阅读理解', 'full_word' : '阅读理解题/阅读理解能力测试/阅读理解并选择适合的选项'},
                    {'type' : '6', 'key_word' : '根据短文内容选择正确答案', 'full_word' : '根据短文内容选择正确答案'},
                    {'type' : '6', 'key_word' : '阅读技能', 'full_word' : '阅读技能'},
                    {'type' : '6', 'key_word' : '图表理解', 'full_word' : '图表理解'},
                    {'type' : '6', 'key_word' : '短文理解', 'full_word' : '短文理解'},
                    {'type' : '6', 'key_word' : r'^.*?阅读短文.*?根据短文内容.*?$', 'full_word' : '阅读短文，根据短文内容，从短文后的五个选项中选出能填入空白处的最佳选项'},
                    {'type' : '6', 'key_word' : '阅读还原短文', 'full_word' : '阅读还原短文'},
                    {'type' : '6', 'key_word' : '阅读下列短文', 'full_word' : '阅读下列短文，根据短文内容从短文中选出最佳选项'},
                    
                    # {'type' : '7', 'key_word' : '作文', 'full_word' : '作文题/情景作文'},
                    {'type' : '7', 'key_word' : '书面表达', 'full_word' : '书面表达'},
                    {'type' : '7', 'key_word' : '写作', 'full_word' : '写作'},
                    {'type' : '7', 'key_word' : '文段表达', 'full_word' : '文段表达'},
                    {'type' : '7', 'key_word' : '仿写', 'full_word' : '仿写'},
                    {'type' : '7', 'key_word' : '看图写话', 'full_word' : '看图写话'},
                    {'type' : '7', 'key_word' : '写回信', 'full_word' : '写回信'},

                    # {'type' : '8', 'key_word' : '翻译', 'full_word' : '翻译题/翻译下列句子/将下列句子翻译成中文/将下列句子翻译成英文/语篇翻译，阅读下面短文，将划线部分译成英文或中文'},
                    {'type' : '8', 'key_word' : '最佳译文', 'full_word' : '选择句子的最佳译文'},
                    {'type' : '8', 'key_word' : '中翻英', 'full_word' : '中翻英'},
                    {'type' : '8', 'key_word' : '英翻中', 'full_word' : '英翻中'},
                    {'type' : '8', 'key_word' : '中译英', 'full_word' : '中译英'},
                    {'type' : '8', 'key_word' : '英译中', 'full_word' : '英译中'},
                    {'type' : '8', 'key_word' : '英汉互译', 'full_word' : '英汉互译'},
                    {'type' : '8', 'key_word' : '词组译成英语', 'full_word' : '词组译成英语'},
                    {'type' : '8', 'key_word' : '根据汉语意思用恰当的单词完成英文句子', 'full_word' : '根据汉语意思用恰当的单词完成英文句子'},

                    {'type' : '9', 'key_word' : '选择合适的单词或短语完成句子', 'full_word' : '看图选择合适的单词或短语完成句子，并将序号填入括号内。'},
                    {'type' : '9', 'key_word' : '选择适合的单词并用其正确的形式完成下列短文', 'full_word' : '从方框中选择适合的单词并用其正确的形式完成下列短文，每个单词只能用一次。'},
                    {'type' : '9', 'key_word' : '短文填空', 'full_word' : '短文填空。从方框中选择正确选项，完成短文。'},
                    {'type' : '9', 'key_word' : '短文选单词', 'full_word' : '读短文选单词。'},
                    {'type' : '9', 'key_word' : '根据短文内容', 'full_word' : '根据短文内容，从选项中选出能填入空白处的最佳选项，选项中有两项为多余选项'},
                    {'type' : '9', 'key_word' : '词语应用', 'full_word' : '词语应用(运用)'},
                    

                    # {'type' : '10', 'key_word' : '改错', 'full_word' : '短文改错/改错题'},
                    {'type' : '10', 'key_word' : '找出题中的错误', 'full_word' : '请找出题中的错误'},
                    
                    # {'type' : '11', 'key_word' : r'^.*?七.*?五.*?$', 'full_word' : '七选五/七选五题/七选五阅读'},
                    {'type' : '11', 'key_word' : r'^.*?7.*?5.*?$', 'full_word' : '口语运用。阅读下面对话，从方框内7个选项中选择5个恰当的句子完成此对话'},
                    {'type' : '11', 'key_word' : '有两个多余选项', 'full_word' : '补全对话，根据情景从方框中选择恰当的句子完成对话（有两个多余选项）。'},
                    {'type' : '11', 'key_word' : '两项为多余选项', 'full_word' : '根据短文内容，从短文后的选项中选出能填入空白处的最佳选项。选项中有两项为多余选项。'},
                    {'type' : '11', 'key_word' : '从方框中选择合适的选项完成对话', 'full_word' : '从方框中选择合适的选项完成对话。'},
                    {'type' : '11', 'key_word' : '七个选项中', 'full_word' : '根据材料内容， 从下面七个选项中选出空缺处的最佳选项，使短文意思通顺、内容完整。'},
                    

                    # {'type' : '12', 'key_word' : '听力', 'full_word' : '听力/听力部分/听力理解/听力测试/听力技能'},

                    # {'type' : '13', 'key_word' : '匹配题', 'full_word' : '匹配题'},
                    {'type' : '13', 'key_word' : '从右栏中找出左栏的', 'full_word' : '从右栏中找出左栏的答语'},
                    {'type' : '13', 'key_word' : 'B栏中找出A栏相应的', 'full_word' : '情景交际，请从B栏中找出A栏相应的答语'},
                    {'type' : '13', 'key_word' : '句子搭配', 'full_word' : '句子搭配'},
                    {'type' : '13', 'key_word' : '选出适当回应句', 'full_word' : '选出适当回应句'},
                    {'type' : '13', 'key_word' : '句子连线', 'full_word' : '句子连线'},
                    {'type' : '13', 'key_word' : '把句子和相应的翻译连起来', 'full_word' : '把句子和相应的翻译连起来'},

                    # {'type' : '14', 'key_word' : '改错', 'full_word' : '改错/短文改错'},
                    {'type' : '14', 'key_word' : '有错就改', 'full_word' : '有错就改'},

                ],
                4:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '4', 'key_word' : '简答', 'full_word' : '简答题'},
                    {'type' : '5', 'key_word' : '计算', 'full_word' : '计算题'},
                    {'type' : '6', 'key_word' : '作图', 'full_word' : '作图题'},
                    {'type' : '7', 'key_word' : '实验探究', 'full_word' : '实验探究题'},

                ],
                5:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '4', 'key_word' : '简答', 'full_word' : '简答题'},
                    {'type' : '5', 'key_word' : '计算', 'full_word' : '计算题'},
                    {'type' : '6', 'key_word' : '实验', 'full_word' : '实验题'},
                    {'type' : '9', 'key_word' : '推断', 'full_word' : '推断题'},
                 ],
                6:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题'},
                    {'type' : '4', 'key_word' : '匹配', 'full_word' : '匹配题'},
                    {'type' : '5', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '6', 'key_word' : '综合', 'full_word' : '综合题'},
                    {'type' : '7', 'key_word' : '探究', 'full_word' : '探究题'},
                 ],
                7:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题'},
                    {'type' : '4', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '5', 'key_word' : '简答', 'full_word' : '简答题'},
                    {'type' : '6', 'key_word' : '论述', 'full_word' : '论述题'},
                    {'type' : '7', 'key_word' : '匹配', 'full_word' : '匹配题'},
                 ],
                8:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题'},
                    {'type' : '4', 'key_word' : '匹配', 'full_word' : '匹配题'},
                    {'type' : '5', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '6', 'key_word' : '改错', 'full_word' : '改错题'},
                    {'type' : '7', 'key_word' : '材料分析', 'full_word' : '材料分析题'},
                    {'type' : '8', 'key_word' : '简答', 'full_word' : '简答题'},
                 ],
                9:
                [{'type' : '1', 'key_word' : '选择', 'full_word' : '选择题'},
                    {'type' : '1', 'key_word' : '单选', 'full_word' : '单选题'},
                    {'type' : '2', 'key_word' : '多项选择', 'full_word' : '多项选择题'},
                    {'type' : '2', 'key_word' : '多选', 'full_word' : '多项选择题'},
                    {'type' : '3', 'key_word' : '判断', 'full_word' : '判断题'},
                    {'type' : '4', 'key_word' : '匹配', 'full_word' : '匹配题'},
                    {'type' : '5', 'key_word' : '填空', 'full_word' : '填空题'},
                    {'type' : '6', 'key_word' : '简答', 'full_word' : '简答题'},
                    {'type' : '7', 'key_word' : '作图', 'full_word' : '作图题'},
                    {'type' : '8', 'key_word' : '综合', 'full_word' : '综合题'},
                 ],
            }
